import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import clsx from "clsx";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const MANROPE_FONT = localFont({
  src: [
    {
      path: "../../public/assets/fonts/Manrope-ExtraLight.ttf",
      weight: "100",
      style: "extralight",
    },

    {
      path: "../../public/assets/fonts/Manrope-Light.ttf",
      weight: "200",
      style: "light",
    },

    {
      path: "../../public/assets/fonts/Manrope-Regular.ttf",
      weight: "300",
      style: "normal",
    },

    {
      path: "../../public/assets/fonts/Manrope-Medium.ttf",
      weight: "400",
      style: "medium",
    },

    {
      path: "../../public/assets/fonts/Manrope-Bold.ttf",
      weight: "600",
      style: "bold",
    },

    {
      path: "../../public/assets/fonts/Manrope-SemiBold.ttf",
      weight: "700",
      style: "semiBold",
    },

    {
      path: "../../public/assets/fonts/Manrope-ExtraBold.ttf",
      weight: "800",
      style: "extraBold",
    },
  ],
  display: "swap",
  variable: "--font-manrope",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={clsx(
          MANROPE_FONT.variable,
          "flex flex-col min-h-screen"
        )}
      >
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
